"""Take the judge off home-made data: measure it on BIRD dev, a public human-written
Text-to-SQL benchmark, against the public metric it is supposed to reproduce.

Why this exists. Every calibration number in `README` was produced on a benchmark this
repository generated itself - template questions, template gold SQL, a schema nobody
else has seen. Three rounds of review named that as the load-bearing weakness
(`docs/HANDOFF.md` §6: 题目全部来自参数化模板). Self-auditing a judge on home-made data
proves the judge is consistent, not that it measures what the field calls execution
accuracy. So this script puts the same judge on real schemas with real hand-written gold
SQL and compares, question by question, against the public-benchmark rule.

What it measures, at zero API cost (no model is called - the injected variants are
generated by `sqlagent.llm.corrupt`, the same function the mock provider uses):

  A. gold vs gold - every BIRD gold that runs on its own database must be judged
     correct by both sides. Any disagreement here is a bug, not a finding.
  B. gold vs my six injected defect classes - my verdict against the verdict the policy
     predicts (`result_differs`, quantised to my own tolerance), and against the public
     set-semantics verdict. Divergences are the interesting output, and they are
     classified rather than averaged away.

Determinism: no RNG. The subset is the first N question_ids of each BIRD difficulty tier
after sorting, so re-running picks the same questions.

Exclusions are counted and reported with a reason - a gold SQL that cannot execute on
SQLite, or that a read-only allowlist refuses, is data about the benchmark and about the
guard, not noise to discard silently.

Run:  python scripts/bird_judge.py --dev-dir <path to extracted BIRD dev>
Cost: 0. Nothing leaves the machine; the databases are read-only.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sqlagent import db  # noqa: E402
from sqlagent.eval.scoring import execute, grade, result_differs, score_execution  # noqa: E402
from sqlagent.llm import corrupt  # noqa: E402
from sqlagent.stats import PRESENTATION_ONLY_MODES  # noqa: E402

MODES = ["reflow", "reorder_cols", "float_round", "drop_distinct", "wrong_limit", "bad_column"]
# The public rule, spelled out rather than gestured at: BIRD's submission checker and
# Spider's evaluation_ex both compare result *sets*, so row order, duplicate rows and
# column naming are all invisible to them. That is the comparison worth making, because
# "our judge agrees with the benchmark" and "our judge is strictly more sensitive than
# the benchmark" are different claims and only one of them is true.
PUBLIC_RULE = "set(gold_rows) == set(pred_rows), order- and duplicate-blind"


def bird_databases(dev_dir: Path) -> dict[str, Path]:
    out = {}
    for d in sorted(p for p in dev_dir.iterdir() if p.is_dir()):
        sqlite = next(iter(sorted(d.glob("*.sqlite"))), None) or next(iter(sorted(d.glob("*.db"))), None)
        if sqlite:
            out[d.name] = sqlite
    return out


def load_gold(dev_dir: Path) -> list[dict]:
    for name in ("dev.json", "dev_light.json", "live_dev.json"):
        p = dev_dir / name
        if p.exists():
            rows = json.loads(p.read_text(encoding="utf-8"))
            for r in rows:
                r["_source"] = name
            return rows
    raise SystemExit(f"no dev.json in {dev_dir} - got {sorted(p.name for p in dev_dir.iterdir())[:8]}")


def pick(rows: list[dict], per_tier: int) -> list[dict]:
    """First `per_tier` question_ids of each difficulty tier, sorted. No RNG, so the
    same questions come back on any machine."""
    by_tier: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_tier[str(r.get("difficulty") or "unknown")].append(r)
    chosen = []
    for tier in sorted(by_tier):
        chosen.extend(sorted(by_tier[tier], key=lambda r: int(r["question_id"]))[:per_tier])
    return chosen


def public_verdict(gold_rows: list, pred_rows: list) -> bool:
    def key(rows):
        return {tuple("" if v is None else str(v) for v in row) for row in rows}
    return key(gold_rows) == key(pred_rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dev-dir", default=str(ROOT.parent / ".external" / "dev"))
    ap.add_argument("--per-tier", type=int, default=40)
    ap.add_argument("--out", default=str(ROOT / "results" / "bird-judge.jsonl"))
    args = ap.parse_args()

    dev_dir = Path(args.dev_dir)
    if not dev_dir.is_dir():
        raise SystemExit(
            f"{dev_dir} not found. Download BIRD dev (~346 MB, no key needed):\n"
            f"  curl -o dev.zip https://bird-bench.oss-cn-beijing.aliyuncs.com/dev.zip\n"
            f"  unzip dev.zip -d {dev_dir.parent}\n"
            "This experiment is $0 and calls no model; it is deliberately not in CI, "
            "because a 346 MB third-party download does not belong in a build.")
    dbs = bird_databases(dev_dir)
    rows = pick(load_gold(dev_dir), args.per_tier)
    print(f"BIRD dev: {len(dbs)} databases with a SQLite file, {len(rows)} questions selected "
          f"({args.per_tier}/difficulty tier, sorted by question_id)")

    out_rows: list[dict] = []
    skipped: Counter[str] = Counter()
    per_mode = {m: {"checked": 0, "policy_agree": 0, "public_agree": 0,
                    "mine_strict": 0, "mine_lenient": 0} for m in MODES}
    gold_ok = gold_bad = 0
    divergence_kinds: Counter[str] = Counter()

    for r in rows:
        db_id = str(r.get("db_id") or r.get("DB") or "")
        gold_sql = str(r.get("SQL") or r.get("gold_sql") or "")
        path = dbs.get(db_id)
        if not path or not gold_sql.strip():
            skipped["no database or no gold SQL"] += 1
            continue
        conn = db.connect_ro(path)
        try:
            gold = execute(conn, gold_sql)
            if not gold.ok:
                skipped[f"gold SQL refused or failed on SQLite: {gold.error_type}"] += 1
                continue
            if not gold.rows:
                skipped["gold result empty (nothing to compare)"] += 1
                continue
            # A. gold vs gold.
            if score_execution(gold, gold, require_order=False).correct:
                gold_ok += 1
            else:
                gold_bad += 1
                out_rows.append({"question_id": r["question_id"], "db_id": db_id, "mode": "self",
                                 "mine": False, "public": public_verdict(gold.rows, gold.rows),
                                 "note": "gold judged against itself"})
            # B. gold vs injected defects.
            for mode in MODES:
                try:
                    cor_sql, applied = corrupt(gold_sql, mode)
                except Exception as exc:  # a gold the rewriter cannot parse is data, not a crash
                    skipped[f"corrupt() failed: {type(exc).__name__}"] += 1
                    continue
                if not applied:
                    skipped[f"{mode}: cannot be injected into this query"] += 1
                    continue
                pred = execute(conn, cor_sql)
                if not pred.ok:
                    # bad_column is *meant* to fail to execute; the rest are not.
                    v_mine = {"correct": False, "reason": pred.error_type}
                else:
                    v = score_execution(gold, pred, require_order=False)
                    v_mine = {"correct": v.correct, "reason": v.reason}
                v_public = public_verdict(gold.rows, pred.rows) if pred.ok else False
                changed = result_differs(gold, pred) if pred.ok else True
                expected = mode in PRESENTATION_ONLY_MODES or not changed
                d = per_mode[mode]
                d["checked"] += 1
                d["policy_agree"] += int(v_mine["correct"] == expected)
                d["public_agree"] += int(v_mine["correct"] == v_public)
                if v_mine["correct"] != v_public:
                    if not v_mine["correct"] and v_public:
                        d["mine_strict"] += 1
                        divergence_kinds[f"{mode}: public metric blind"] += 1
                    else:
                        d["mine_lenient"] += 1
                        divergence_kinds[f"{mode}: public metric stricter"] += 1
                out_rows.append({"question_id": r["question_id"], "db_id": db_id, "mode": mode,
                                 "mine": v_mine["correct"], "mine_reason": v_mine["reason"],
                                 "public": v_public, "expected_by_policy": expected,
                                 "result_changed": bool(changed),
                                 "sql_len": len(cor_sql)})
        finally:
            conn.close()

    checked = sum(d["checked"] for d in per_mode.values())
    print(f"\ngold judged correct against itself : {gold_ok}/{gold_ok + gold_bad}")
    if gold_bad:
        print("  *** this is a bug, not a finding - see results/bird-judge.jsonl mode=self")
    print(f"injected observations checked        : {checked}")
    print(f"\n{'mode':<14}{'checked':>8}{'vs policy':>11}{'vs public':>11}{'I stricter':>12}{'I looser':>10}")
    for mode in MODES:
        d = per_mode[mode]
        if not d["checked"]:
            print(f"{mode:<14}{0:>8}   (no query here could carry this defect - reported, not hidden)")
            continue
        print(f"{mode:<14}{d['checked']:>8}{d['policy_agree']/d['checked']:>10.1%}"
              f"{d['public_agree']/d['checked']:>11.1%}{d['mine_strict']:>12}{d['mine_lenient']:>10}")

    print("\n与公开口径分歧的分类（这才是这次实验的产物，一致率不是）：")
    for kind, n in divergence_kinds.most_common():
        print(f"  {n:>4}  {kind}")
    print(f"\n公开基准的比较规则（被对比的一方）：{PUBLIC_RULE}")
    print("跳过的题（逐类报告，不静默丢弃）：")
    for reason, n in skipped.most_common():
        print(f"  {n:>4}  {reason}")

    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps({"_summary": {
            "provider": "none (no model called)", "sqlite_version": sqlite3.sqlite_version,
            "source": sorted({r['_source'] for r in rows}), "databases": len(dbs),
            "questions_selected": len(rows), "checked": checked,
            "per_mode": per_mode, "skipped": dict(skipped),
            "gold_self_correct": gold_ok, "gold_self_wrong": gold_bad,
            "public_rule": PUBLIC_RULE,
        }}, ensure_ascii=False) + "\n")
        for row in out_rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
